version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    links:
      - mysql
    volumes:
      - ./nginx/src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:8081"

  apache:
    container_name: php-apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mysql
    volumes:
      - ./apache/src:/var/www/html