version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - ./src:/var/www/html/

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
    ports:
      - "8081:80"
    volumes:
      - ./data:/docker-entrypoint-initdb.d